# MySQL配置
mysql:
  host: "124.222.151.35"  # 数据库地址
  port: "3306"  # 数据库端口
  user: root  # 数据库用户名
  pwd: "abc123456::"  # 数据库密码
  dbname: ai  # 数据库名

# Redis配置
redis:
  host: "124.222.151.35"  # Redis地址
  port: "6379"  # Redis端口
  pwd: "123456"  # Redis密码

# 邮件配置
email:
  addr: "smtp.example.com:587"  # SMTP服务器地址和端口
  host: "smtp.example.com"  # SMTP服务器主机名
  from: "AI简历助手"  # 发件人名称
  email: "noreply@example.com"  # 发件人邮箱
  auth: "your-email-password"  # 邮箱密码或授权码
